version: "3.7"
services:
  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - 6379:6379
    expose:
      - 6379

  api:
    build: .
    container_name: api
    restart: unless-stopped

    ports:
      - "3040:3040"
